# Generated by Django 3.2.10 on 2021-12-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minetitel', models.TextField(verbose_name='minetitel')),
                ('createTime', models.DateField()),
                ('updateTime', models.DateField()),
                ('titel1', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('contentblog1', models.TextField(blank=True, null=True, verbose_name='content')),
                ('iamge1', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image')),
                ('titel2', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('contentblog2', models.TextField(blank=True, null=True, verbose_name='content')),
                ('iamge2', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image')),
                ('titel3', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('contentblog3', models.TextField(blank=True, null=True, verbose_name='content')),
                ('iamge3', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image')),
                ('titel4', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('contentblog4', models.TextField(blank=True, null=True, verbose_name='content')),
                ('iamge4', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
