# Generated by Django 3.2.7 on 2022-02-05 12:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='minetitel',
            new_name='titel',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contentblog1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contentblog2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contentblog3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contentblog4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='titel1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='titel2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='titel3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='titel4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updateTime',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='createTime',
            field=models.DateField(verbose_name='date'),
        ),
    ]
