# Generated by Django 3.2.7 on 2022-02-06 21:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20220205_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True),
        ),
    ]
