# Generated by Django 3.2.7 on 2022-02-22 14:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20220222_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel1', models.CharField(blank=True, max_length=50, null=True, verbose_name='titel')),
                ('content1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True)),
                ('iamge1', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image')),
                ('iamge11', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content10',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content6',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content7',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content8',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content9',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge10',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge1010',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge11',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge22',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge33',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge44',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge55',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge6',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge66',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge7',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge77',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge8',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge88',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge9',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='iamge99',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='titel1',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.content', verbose_name='content'),
        ),
    ]
