# Generated by Django 3.2.7 on 2022-02-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0003_alter_youtube_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='utls_aparat',
            field=models.URLField(null=True, verbose_name='utls_aparat'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='utls_youtube',
            field=models.URLField(null=True, verbose_name='utls_youtube'),
        ),
    ]
