# Generated by Django 3.2.7 on 2022-02-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0004_auto_20220207_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='Summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Summary'),
        ),
    ]
