# Generated by Django 3.2.10 on 2021-12-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='content')),
                ('createTime', models.DateField(verbose_name='Date')),
                ('imagecontent', models.ImageField(upload_to=None, verbose_name='iamge')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
    ]
